// ABOUTME: Decrypts Granola's encrypted session blob (storage.dek + supabase.json.enc)
// ABOUTME: Two-level scheme: Electron safeStorage (AES-128-CBC) wraps a 32-byte DEK used for AES-256-GCM

use crate::{Error, Result};
use aes::Aes128;
use aes_gcm::aead::Aead;
use aes_gcm::{Aes256Gcm, KeyInit, Nonce};
use base64::Engine;
use cbc::cipher::{block_padding::Pkcs7, BlockDecryptMut, KeyIvInit};
use sha1::Sha1;
use std::fs;
use std::path::Path;
use zeroize::Zeroizing;

const SAFE_STORAGE_PREFIX: &[u8; 3] = b"v10";
const SAFE_STORAGE_SALT: &[u8; 9] = b"saltysalt";
const SAFE_STORAGE_ITERATIONS: u32 = 1003;
const SAFE_STORAGE_KEY_LEN: usize = 16;
const SAFE_STORAGE_IV: [u8; 16] = [b' '; 16];

const DEK_LEN: usize = 32;
const GCM_NONCE_LEN: usize = 12;
const GCM_TAG_LEN: usize = 16;

const KEYCHAIN_SERVICE: &str = "Granola Safe Storage";
const KEYCHAIN_ACCOUNT: &str = "Granola Key";

type Aes128CbcDec = cbc::Decryptor<Aes128>;

/// Decrypts Granola's encrypted session by reading `storage.dek` and
/// `supabase.json.enc` from `session_dir` and fetching the safeStorage
/// password from the macOS Keychain.
pub fn decrypt_session(session_dir: &Path) -> Result<String> {
    let dek_path = session_dir.join("storage.dek");
    let enc_path = session_dir.join("supabase.json.enc");

    let kc_pw = read_keychain_password()?;

    let dek_blob = fs::read(&dek_path)
        .map_err(|e| Error::Auth(format!("read {}: {e}", dek_path.display())))?;
    let dek = decrypt_dek(&dek_blob, kc_pw.as_bytes())?;

    let enc_blob = fs::read(&enc_path)
        .map_err(|e| Error::Auth(format!("read {}: {e}", enc_path.display())))?;
    let plaintext = decrypt_enc(&enc_blob, &dek)?;

    String::from_utf8(plaintext)
        .map_err(|e| Error::Auth(format!("decrypted session is not utf-8: {e}")))
}

fn read_keychain_password() -> Result<Zeroizing<String>> {
    let entry = keyring::Entry::new(KEYCHAIN_SERVICE, KEYCHAIN_ACCOUNT)
        .map_err(|e| Error::Auth(format!("keyring entry init failed: {e}")))?;
    let pw = entry
        .get_password()
        .map_err(|e| Error::Auth(format!("keychain access failed: {e}")))?;
    Ok(Zeroizing::new(pw))
}

fn decrypt_dek(blob: &[u8], password: &[u8]) -> Result<Zeroizing<Vec<u8>>> {
    if !blob.starts_with(SAFE_STORAGE_PREFIX) {
        return Err(Error::Auth(format!(
            "storage.dek missing v10 prefix (got {:?})",
            &blob[..blob.len().min(3)]
        )));
    }
    let ciphertext = &blob[SAFE_STORAGE_PREFIX.len()..];

    let mut key = Zeroizing::new([0u8; SAFE_STORAGE_KEY_LEN]);
    pbkdf2::pbkdf2_hmac::<Sha1>(
        password,
        SAFE_STORAGE_SALT,
        SAFE_STORAGE_ITERATIONS,
        key.as_mut_slice(),
    );

    let mut buf = ciphertext.to_vec();
    let plaintext = Aes128CbcDec::new((&*key).into(), &SAFE_STORAGE_IV.into())
        .decrypt_padded_mut::<Pkcs7>(&mut buf)
        .map_err(|e| Error::Auth(format!("safeStorage CBC decrypt failed: {e}")))?;

    let dek_b64 = std::str::from_utf8(plaintext)
        .map_err(|e| Error::Auth(format!("safeStorage plaintext not utf-8: {e}")))?;
    let dek = base64::engine::general_purpose::STANDARD
        .decode(dek_b64.trim())
        .map_err(|e| Error::Auth(format!("base64 decode DEK failed: {e}")))?;

    if dek.len() != DEK_LEN {
        return Err(Error::Auth(format!(
            "expected {DEK_LEN}-byte DEK, got {}",
            dek.len()
        )));
    }
    Ok(Zeroizing::new(dek))
}

fn decrypt_enc(blob: &[u8], dek: &[u8]) -> Result<Vec<u8>> {
    if blob.len() < GCM_NONCE_LEN + GCM_TAG_LEN {
        return Err(Error::Auth(format!(
            "supabase.json.enc too short ({} bytes)",
            blob.len()
        )));
    }
    let nonce_arr: [u8; GCM_NONCE_LEN] = blob[..GCM_NONCE_LEN]
        .try_into()
        .map_err(|e| Error::Auth(format!("nonce slice: {e}")))?;
    let nonce = Nonce::from(nonce_arr);
    let ciphertext_and_tag = &blob[GCM_NONCE_LEN..];

    let cipher = Aes256Gcm::new_from_slice(dek)
        .map_err(|e| Error::Auth(format!("AES-256-GCM key init failed: {e}")))?;
    cipher
        .decrypt(&nonce, ciphertext_and_tag)
        .map_err(|e| Error::Auth(format!("AES-256-GCM decrypt failed: {e}")))
}

#[cfg(test)]
mod tests {
    use super::*;
    use aes_gcm::aead::Aead;
    use cbc::cipher::{block_padding::Pkcs7, BlockEncryptMut, KeyIvInit};

    type Aes128CbcEnc = cbc::Encryptor<Aes128>;

    // === Synthetic vectors generated by /tmp/gen_vector.py ===
    // kc_pw = b"test-password"
    // DEK   = bytes(range(32))
    // nonce = 0102030405060708090a0b0c
    const TEST_KC_PW: &[u8; 13] = b"\x74\x65\x73\x74\x2d\x70\x61\x73\x73\x77\x6f\x72\x64";

    const TEST_DEK: [u8; 32] = [
        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e,
        0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d,
        0x1e, 0x1f,
    ];

    const TEST_DEK_BLOB: &[u8; 51] = b"\x76\x31\x30\xe2\x31\xa6\xb2\x21\xf3\x7b\xb7\xbb\x6c\x18\x53\x26\x99\x94\x60\xa4\xa4\xa5\x9f\xd7\x07\x26\xc6\x51\xca\x65\xe1\x08\x78\x3f\xb9\x8b\xf3\x50\x2f\x9b\xd2\x8d\x4e\x7d\x28\x5e\x10\xc2\x43\x8a\xe5";

    const TEST_ENC_BLOB: &[u8; 102] = b"\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x7e\xc8\x29\xb0\x9f\xe7\x99\xe9\x22\xfd\x0a\x23\x32\x29\xc8\x49\x20\x20\xc3\xd2\xb5\x1a\x3f\xb7\xca\x30\x8a\x7b\xea\xd9\x1d\xa0\xea\x97\xb9\xe5\x4c\xce\xb0\xbd\xd1\xcf\xd9\x80\xb6\xa8\xa7\x29\xf1\x9d\x2a\x8e\x88\xbb\x0c\x2d\x14\x17\x7b\xb9\x41\x63\x5b\x68\x0e\x53\x78\x4a\xd8\xad\x7f\x9d\x69\x6f\x2d\xeb\x9d\x93\x3b\xf7\x62\x77\x37\xd7\x5c\x58\xbc\x78\xf1\x24";

    const TEST_PLAINTEXT: &[u8; 74] = b"\x7b\x22\x73\x65\x73\x73\x69\x6f\x6e\x5f\x69\x64\x22\x3a\x22\x61\x62\x63\x22\x2c\x22\x77\x6f\x72\x6b\x6f\x73\x5f\x74\x6f\x6b\x65\x6e\x73\x22\x3a\x22\x7b\x5c\x22\x61\x63\x63\x65\x73\x73\x5f\x74\x6f\x6b\x65\x6e\x5c\x22\x3a\x5c\x22\x6a\x77\x74\x2e\x62\x6f\x64\x79\x2e\x73\x69\x67\x5c\x22\x7d\x22\x7d";

    #[test]
    fn decrypts_dek_against_known_python_vector() {
        let dek = decrypt_dek(TEST_DEK_BLOB, TEST_KC_PW).unwrap();
        assert_eq!(&dek[..], &TEST_DEK[..]);
    }

    #[test]
    fn decrypts_enc_against_known_python_vector() {
        let pt = decrypt_enc(TEST_ENC_BLOB, &TEST_DEK).unwrap();
        assert_eq!(&pt[..], &TEST_PLAINTEXT[..]);
    }

    #[test]
    fn dek_decrypt_rejects_missing_v10_prefix() {
        let bad = b"v09\x00\x01\x02";
        let err = decrypt_dek(bad, TEST_KC_PW).unwrap_err();
        assert!(
            err.to_string().contains("v10"),
            "error should mention v10: {err}"
        );
    }

    #[test]
    fn dek_decrypt_rejects_wrong_password() {
        let err = decrypt_dek(TEST_DEK_BLOB, b"wrong-password").unwrap_err();
        // Wrong password yields invalid PKCS#7 padding (probabilistic) or
        // non-base64 plaintext; both are surfaced as Auth errors.
        let msg = err.to_string();
        assert!(
            msg.contains("CBC") || msg.contains("base64") || msg.contains("utf-8"),
            "wrong password should fail decode somewhere: {msg}"
        );
    }

    #[test]
    fn enc_decrypt_rejects_short_blob() {
        let err = decrypt_enc(b"too-short", &TEST_DEK).unwrap_err();
        assert!(err.to_string().contains("too short"));
    }

    #[test]
    fn enc_decrypt_rejects_tampered_tag() {
        let mut tampered = TEST_ENC_BLOB.to_vec();
        let last = tampered.len() - 1;
        tampered[last] ^= 0x01;
        let err = decrypt_enc(&tampered, &TEST_DEK).unwrap_err();
        assert!(
            err.to_string().contains("GCM"),
            "tampered tag should fail GCM auth: {err}"
        );
    }

    #[test]
    fn enc_decrypt_rejects_wrong_dek() {
        let mut wrong = TEST_DEK;
        wrong[0] ^= 0xff;
        let err = decrypt_enc(TEST_ENC_BLOB, &wrong).unwrap_err();
        assert!(err.to_string().contains("GCM"));
    }

    #[test]
    fn dek_round_trip_succeeds() {
        let pw = b"another-password";
        let dek = [0xab; 32];

        let blob = encrypt_dek_for_test(&dek, pw);
        let decrypted = decrypt_dek(&blob, pw).unwrap();
        assert_eq!(&decrypted[..], &dek[..]);
    }

    #[test]
    fn enc_round_trip_succeeds() {
        let dek = [0xcd; 32];
        let plaintext = b"hello session";
        let nonce = [0u8; 12];

        let blob = encrypt_enc_for_test(plaintext, &dek, &nonce);
        let decrypted = decrypt_enc(&blob, &dek).unwrap();
        assert_eq!(decrypted, plaintext);
    }

    fn encrypt_dek_for_test(dek: &[u8], password: &[u8]) -> Vec<u8> {
        let mut key = [0u8; SAFE_STORAGE_KEY_LEN];
        pbkdf2::pbkdf2_hmac::<Sha1>(
            password,
            SAFE_STORAGE_SALT,
            SAFE_STORAGE_ITERATIONS,
            &mut key,
        );
        let dek_b64 = base64::engine::general_purpose::STANDARD.encode(dek);
        let mut buf = vec![0u8; dek_b64.len() + 16];
        let ct_len = Aes128CbcEnc::new(&key.into(), &SAFE_STORAGE_IV.into())
            .encrypt_padded_b2b_mut::<Pkcs7>(dek_b64.as_bytes(), &mut buf)
            .unwrap()
            .len();
        buf.truncate(ct_len);
        let mut out = SAFE_STORAGE_PREFIX.to_vec();
        out.extend_from_slice(&buf);
        out
    }

    fn encrypt_enc_for_test(plaintext: &[u8], dek: &[u8], nonce: &[u8; GCM_NONCE_LEN]) -> Vec<u8> {
        let cipher = Aes256Gcm::new_from_slice(dek).unwrap();
        let nonce_ga = Nonce::from(*nonce);
        let ct_and_tag = cipher.encrypt(&nonce_ga, plaintext.as_ref()).unwrap();
        let mut out = nonce.to_vec();
        out.extend_from_slice(&ct_and_tag);
        out
    }
}
